version: '3.8'
services:
  stats-server:
    build: stats-server/
    image: "stats-server-image"
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

    environment:
      - DB_NAME=statServiceDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5437:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statServiceDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  ewm-service:
    build: ewm-service/
    ports:
      - "8080:8080"
    image: "ewm-service-image"
    container_name: ewm-service
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=ewnServiceDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    depends_on:
      - stats-server
    environment:
      - POSTGRES_DB=ewnServiceDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234